//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace Contracts.ManagerToWorker {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ccfit.nsu.ru/schema/crack-hash-request")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ccfit.nsu.ru/schema/crack-hash-request", IsNullable=false)]
    public partial class CrackHashManagerRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private int partNumberField;
        
        private int partCountField;
        
        private string hashField;
        
        private int maxLengthField;
        
        private string[] alphabetField;
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        public int PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        public int PartCount {
            get {
                return this.partCountField;
            }
            set {
                this.partCountField = value;
                this.RaisePropertyChanged("PartCount");
            }
        }
        
        /// <remarks/>
        public string Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
                this.RaisePropertyChanged("Hash");
            }
        }
        
        /// <remarks/>
        public int MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
                this.RaisePropertyChanged("MaxLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("symbols", IsNullable=false)]
        public string[] Alphabet {
            get {
                return this.alphabetField;
            }
            set {
                this.alphabetField = value;
                this.RaisePropertyChanged("Alphabet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
